Repository VirtusLab/git-machete-intellij-plugin, pull requests merged in 2022-08, with the labels that each got.

#1024 Decouple other modules from frontend:file
  frontend/actions/build.gradle.kts
  frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/defs/FileTypeIds.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/MacheteFileType.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/grammar/MacheteFile.java
  frontend/ui/impl/build.gradle.kts
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/root/GitMachetePanel.java
Labels: build, code quality

#1023 Port update to fork-point criteria (exclude `update by push`) from CLI
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
Labels: bug, backend

#1022 Fix scripts/utils.sh so that no extra newline is printed by machete-status-branch hook in case version cannot be found
  scripts/utils.sh
Labels: bug, minor

#1009 Partially fix the execution of `versionCatalogUpdate` task
  build.gradle.kts
Labels: bug, build

#1012 Share version refs between `[plugins]` and `[libraries]` in libs.versions.toml
  gradle/libs.versions.toml
Labels: build, code quality

#1013 Hack around ben-manes/gradle-versions-plugin#284 by symlinking the version catalog into buildSrc
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/gradle/libs.versions.toml
  buildSrc/settings.gradle.kts
Labels: bug, build

#1018 Bump version-catalog-update Gradle plugin to v0.5.3 to fix the error in `versionCatalogUpdate` task
  CONTRIBUTING.md
  buildSrc/settings.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: bug, build

#1020 Clean up deprecations in build code + restore `kotlinOptions.allWarningsAsErrors`
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/test/kotlin/com/virtuslab/gitmachete/buildsrc/BuildNumberComparisonTest.kt
Labels: build, code quality

#1021 Execute `versionCatalogUpdate` Gradle task from a CircleCI cron job and open PRs with version updates
  .circleci/config.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
  gradle/libs.versions.toml
Labels: ci

#1026 Refactor/1004 simplify libs versions
  build.gradle.kts
  buildSrc/build.gradle.kts
  frontend/file/build.gradle.kts
  gradle/libs.versions.toml
Labels: build, code quality

#1032 Fix formatting of libs.versions.toml to prevent cron from removing the comment
  gradle/libs.versions.toml
Labels: build

#1033 Add ktlint to spotless and apply it
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Checkstyle.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Spotless.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
  buildSrc/src/test/kotlin/com/virtuslab/gitmachete/buildsrc/BuildNumberComparisonTest.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/DeleteBranchOnSlideOutSuggestionDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/GraphTableDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/OverrideForkPointDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/ResetBranchToRemoteInfoDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/SlideInDialog.kt
  frontend/file/build.gradle.kts
  scripts/enforce-settings-gradle-match-directories
  settings.gradle.kts
Labels: build, code quality

#1035 Switch to Kotlin Regex API
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
Labels: code quality

#1038 Un-hardcode property names in method
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
Labels: code quality

#1042 Set up an autoupdater for Gradle wrapper
  .circleci/config.yml
  CONTRIBUTING.md
  docker/Dockerfile
Labels: build, ci

#1041 Add task that looks for new IntelliJ stable releases
  .circleci/config.yml
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt
  buildSrc/src/test/kotlin/com/virtuslab/gitmachete/buildsrc/BuildNumberComparisonTest.kt
Labels: ci, distribution

#1048 Add test for GitMacheteErrorReportSubmitter
  frontend/ui/impl/build.gradle.kts
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java
  frontend/ui/impl/src/test/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitterTest.java
  frontend/ui/impl/src/test/resources/error_report_uri.txt
  frontend/ui/impl/src/test/resources/error_report_uri_with_stacktrace_title.txt
  frontend/ui/impl/src/test/resources/error_report_uri_with_template.txt
Labels: testing

#1053 Avoid updating the properties file when values are the same
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt
Labels: ci

#1054 Change cache map to use SoftReferences
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepositoryCache.java
Labels: bug, backend

#1055 Massage `GitMacheteErrorReportSubmitter` and its tests a bit more
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java
  frontend/ui/impl/src/main/resources/bug_report.md
  frontend/ui/impl/src/test/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitterTest.java
  frontend/ui/impl/src/test/resources/error_report_uri.txt
  frontend/ui/impl/src/test/resources/error_report_uri_with_stacktrace_title.txt
  frontend/ui/impl/src/test/resources/error_report_uri_with_template.txt
  frontend/ui/impl/src/test/resources/expected-error-report-uris/for_multiple_events.txt
  frontend/ui/impl/src/test/resources/expected-error-report-uris/with_stack_trace.txt
  frontend/ui/impl/src/test/resources/expected-error-report-uris/without_stack_trace.txt
Labels: testing, code quality

#1057 Extract further parts of build.gradle.kts to buildSrc/
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/VersionFromGit.kt
  frontend/file/build.gradle.kts
Labels: build, code quality

#1056 Increase Xvfb screen size to mitigate `java.awt.IllegalComponentStateException`s in UI tests
  src/uiTest/resources/ideprobe.conf
Labels: bug, testing

#1062 Simplify the Dockerfile used for CI
  .circleci/config.yml
  CONTRIBUTING.md
  docker/Dockerfile
  docker/entrypoint.sh
Labels: ci, code quality

#1065 Apply miscellaneous pre-v2.2.0 release fixes
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Spotless.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  frontend/resourcebundles/build.gradle.kts
  frontend/resourcebundles/src/test/java/com/virtuslab/gitmachete/resourcebundles/junit/GitMacheteBundlePropertiesTestSuite.java
  gradle/libs.versions.toml
  settings.gradle.kts
  src/test/java/com/virtuslab/archunit/BaseArchUnitTestSuite.java
Labels: build, code quality

#1067 Restore JCEF in CI Docker image
  .circleci/config.yml
  docker/Dockerfile
Labels: bug, ci

#1068 Add libraries for JCEF support in 2021.1 UI tests
  .circleci/config.yml
  docker/Dockerfile
Labels: ci, testing

#1077 In check-for-updates cron, discard uncommitted changes if a branch already exists
  .circleci/config.yml
Labels: bug, ci

#1085 Add a note about plugin versions that remain available after bumping earliestSupportedMajor (closes #1084)
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
Labels: documentation, intellij-support

#1087 Remove unused classes from across the codebase
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/backgroundables/PullCurrentBranchFastForwardOnlyBackgroundable.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/common/CantGetGitMacheteRepositoryException.java
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/GitCoreCannotReadGitFileException.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/GitCoreNoSuchRepositoryException.java
  src/test/java/com/virtuslab/archunit/ClassStructureTestSuite.java
Labels: code quality

#1086 Replace `ui-test.intellij.version` and `ui-test.plugin.path` with env vars
  .circleci/config.yml
  CHANGE-NOTES.html
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  src/uiTest/resources/ide.rhino.js
  src/uiTest/resources/ideprobe.conf
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/RunningIntelliJFixtureExtension.scala
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/UISuite.scala
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/UITestSuite.scala
Labels: testing, code quality

#1080 Ide probe - remove `probe.resolvers.jbr.repositories` configs
  gradle/libs.versions.toml
  src/uiTest/resources/ideprobe.conf
Labels: testing, code quality

#1092 Include event message (distinct from throwable message) in the submitted error reports
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSyncToParentByRebaseAction.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java
  frontend/ui/impl/src/test/resources/expected-error-report-uris/for_multiple_events.txt
  frontend/ui/impl/src/test/resources/expected-error-report-uris/with_stack_trace.txt
  frontend/ui/impl/src/test/resources/expected-error-report-uris/without_stack_trace.txt
Labels: ux

#1066 Use changelog-plugin for change notes file
  .circleci/config.yml
  CHANGE-NOTES.html
  CHANGE-NOTES.md
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  gradle/libs.versions.toml
  scripts/enforce-change-notes-updated-on-pr-to-master
  scripts/enforce-newline-at-eof
Labels: build, distribution

#1098 Apply miscellaneous pre-v3.0.0 release fixes
  CHANGE-NOTES.md
  README.md
  frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/icons/MacheteIcons.java
  frontend/base/src/main/resources/edit.svg
  frontend/base/src/main/resources/edit_dark.svg
  frontend/base/src/main/resources/fastForward.svg
  frontend/base/src/main/resources/fastForward_dark.svg
  frontend/base/src/main/resources/fetch.svg
  frontend/base/src/main/resources/fetch_dark.svg
  frontend/base/src/main/resources/help.svg
  frontend/base/src/main/resources/help_dark.svg
  frontend/base/src/main/resources/incomingChangesOn.svg
  frontend/base/src/main/resources/incomingChangesOn_dark.svg
  frontend/base/src/main/resources/macheteLogoIcon.svg
  frontend/base/src/main/resources/macheteLogoIcon_dark.svg
  frontend/base/src/main/resources/merge.svg
  frontend/base/src/main/resources/merge_dark.svg
  frontend/base/src/main/resources/overrideForkPoint.svg
  frontend/base/src/main/resources/overrideForkPoint_dark.svg
  frontend/base/src/main/resources/pull.svg
  frontend/base/src/main/resources/pull_dark.svg
  frontend/base/src/main/resources/push.svg
  frontend/base/src/main/resources/push_dark.svg
  frontend/base/src/main/resources/rebase.svg
  frontend/base/src/main/resources/rebase_dark.svg
  frontend/base/src/main/resources/refresh.svg
  frontend/base/src/main/resources/refresh_dark.svg
  frontend/base/src/main/resources/reset.svg
  frontend/base/src/main/resources/reset_dark.svg
  frontend/base/src/main/resources/slideIn.svg
  frontend/base/src/main/resources/slideIn_dark.svg
  frontend/base/src/main/resources/slideOut.svg
  frontend/base/src/main/resources/slideOut_dark.svg
  frontend/base/src/main/resources/squash.svg
  frontend/base/src/main/resources/squash_dark.svg
  frontend/base/src/main/resources/toggleListingCommits.svg
  frontend/base/src/main/resources/toggleListingCommits_dark.svg
  frontend/file/build.gradle.kts
  frontend/icons/build.gradle.kts
  scripts/validate-icons
  scripts/validate-markdown-values
  settings.gradle.kts
Labels: code quality, release
