Repository VirtusLab/git-machete-intellij-plugin, pull requests merged in 2022-10, with the labels that each got.

#1200 Bump `io.freefair.gradle:aspectj-plugin` to 6.5.1
  gradle/libs.versions.toml
  version.gradle.kts
Labels: bug, build

#1199 Prohibit calls to java.nio from UI thread, with reasonable exceptions
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/gitrepositoryselection/GitRepositoryComboBox.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  src/test/java/com/virtuslab/archunit/UiThreadUnsafeMethodInvocationsTestSuite.java
Labels: testing, frontend-actions

#1208 Provide `intellijVersions` by `rootProject.extra` instead of an extension
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt
Labels: build, code quality

#1209 Keep IntelliJ versions in a data class + apply other related refactors
  .circleci/config.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/PropertiesHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt
  buildSrc/src/test/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelperTest.kt
  buildSrc/src/test/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionsTest.kt
  intellijVersions.properties
Labels: build, code quality

#1210 Improve the checks for managed branches in `skipNonExistentBranches_toggleListingCommits_slideOutRoot`
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/UITestSuite.scala
Labels: testing, flakiness

#1220 Replacing calls to str.trim().isEmpty() with str.isBlank() issue #1218
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/PreRebaseHookExecutor.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/StatusBranchHookExecutor.java
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileReader.java
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileUtils.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSyncToParentByRebaseAction.java
Labels: code quality

#1222 Improve tips for gradle issues in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1219 Harden UI thread safety
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/StatusBranchHookExecutor.java
  branchLayout/api/build.gradle.kts
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/readwrite/IBranchLayoutReader.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/readwrite/IBranchLayoutWriter.java
  branchLayout/impl/build.gradle.kts
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileReader.java
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileUtils.java
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileWriter.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSlideInBelowAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSlideOutAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/DiscoverAction.java
  frontend/file/build.gradle.kts
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/RediscoverSuggester.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/GitMacheteRepositoryDiscoverer.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/GitMacheteRepositoryUpdateBackgroundable.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  qual/src/main/java/com/virtuslab/qual/guieffect/IgnoreUIThreadUnsafeCalls.java
  src/test/java/com/virtuslab/archunit/UiThreadUnsafeMethodInvocationsTestSuite.java
Labels: code quality

#1217 Prevent NPE in `OpenMacheteFileAction`
  CHANGE-NOTES.md
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/OpenMacheteFileAction.java
Labels: bug, frontend-actions

#1236 Add javadocs to annotations under `qual/`
  config/checker/com.intellij.astub
  config/checker/git4idea.astub
  config/checker/javax.swing.astub
  qual/src/main/java/com/virtuslab/qual/gitmachete/backend/api/ConfirmedLocal.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/backend/api/ConfirmedNonRoot.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/backend/api/ConfirmedRemote.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/backend/api/ConfirmedRoot.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/frontend/graph/api/elements/ConfirmedGraphEdge.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/frontend/graph/api/elements/ConfirmedGraphNode.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/frontend/graph/api/items/ConfirmedBranchItem.java
  qual/src/main/java/com/virtuslab/qual/gitmachete/frontend/graph/api/items/ConfirmedCommitItem.java
  qual/src/main/java/com/virtuslab/qual/guieffect/IgnoreUIThreadUnsafeCalls.java
  qual/src/main/java/com/virtuslab/qual/guieffect/UIThreadUnsafe.java
  qual/src/main/java/com/virtuslab/qual/internal/SubtypingBottom.java
  qual/src/main/java/com/virtuslab/qual/internal/SubtypingTop.java
  src/test/java/com/virtuslab/archunit/UIThreadUnsafeMethodInvocationsTestSuite.java
Labels: documentation

#1224 Bugfix/uitest race condition fix
  CHANGE-NOTES.md
  docs/features.md
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
Labels: bug, testing

#1216 Machete file/generate error for repeated branch
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/highlighting/MacheteAnnotator.java
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
Labels: bug, ux, frontend-editor

#1266 Fix the error submitter issue title
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java
Labels: bug, frontend-ui

#1237 Changed Github release format
  .circleci/config.yml
Labels: ci, release

#1261 Fix `equals` method in `BranchLayout` and `BranchLayoutEntry`
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/BranchLayout.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/BranchLayoutEntry.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/IBranchLayout.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/IBranchLayoutEntry.java
  src/test/java/com/virtuslab/archunit/ForbiddenMethodsTestSuite.java
Labels: bug, code quality, branch-layout

#1269 Explain rationale for using `RuntimeBinding#instantiateSoleImplementingClass` rather than compile-time module dependencies
  binding/src/main/java/com/virtuslab/binding/RuntimeBinding.java
Labels: documentation

#1270 Apply minor improvements before unmanaged branch notification feature - improve the dialog text to omit do getDoNotShowMessage override (ask proper question) - move graph table refresh logic from GitMachetePanel to EnhancedGraphTable
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileReader.java
  branchLayout/impl/src/main/java/com/virtuslab/branchlayout/impl/readwrite/BranchLayoutFileUtils.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseResetToRemoteAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/contextmenu/SyncSelectedToParentByMergeAction.java
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/ResetBranchToRemoteInfoDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/WarnAboutSyncToParentByMergeDialog.kt
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/root/GitMachetePanel.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  scripts/prohibit-properties-unused-keys
Labels: code quality

#1273 Add `commitsUntilParent` in `NonRootManagedBranchSnapshot`; rename `commits` to `uniqueCommits` in this scope
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/INonRootManagedBranchSnapshot.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/NonRootManagedBranchSnapshot.java
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/integration/StatusAndDiscoverIntegrationTestSuite.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSquashAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/SquashCurrentAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/ToggleListingCommitsAction.java
  frontend/graph/impl/src/main/java/com/virtuslab/gitmachete/frontend/graph/impl/repository/RepositoryGraphBuilder.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/DemoGitMacheteRepositorySnapshot.java
Labels: backend, code quality

#1267 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1268 Fix UI thread annotations in GitPushDialog
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/dialogs/GitPushDialog.java
Labels: minor, code quality

#1277 Only include first line of subject in short commit message
  config/checkstyle/checkstyle.xml
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreCommit.java
  gitCore/jGit/src/test/java/com/virtuslab/gitcore/impl/jgit/GitCoreCommitTest.java
  gitCore/jGit/src/test/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepositoryTest.java
  src/test/java/com/virtuslab/archunit/ForbiddenClassesTestSuite.java
Labels: bug, git-core

#1282 Apply fixes before the release v3.1.1
  CHANGE-NOTES.md
  CONTRIBUTING.md
Labels: release

#1158 Use intellij instances downloaded by gradle
  CHANGE-NOTES.md
  gradle/libs.versions.toml
  src/uiTest/resources/ideprobe.conf
  version.gradle.kts
Labels: performance, testing

#1234 if statement have been removed and assertion messages have been appended
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/VersionFromGit.kt
  scripts/enforce-change-notes-updated-on-pr-to-master
  scripts/enforce-version-bump
  scripts/prohibit-direct-merges-to-master
  testCommon/src/testFixtures/java/com/virtuslab/gitmachete/testcommon/TestProcessUtils.java
Labels: testing, code quality

#1243 Feature/alt enter to create non existing branch
  CHANGE-NOTES.md
  frontend/file/build.gradle.kts
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/MacheteFileUtils.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/grammar/MacheteParserDefinition.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/highlighting/MacheteAnnotator.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/quickfix/CreateBranchQuickFix.java
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  src/test/java/com/virtuslab/archunit/UIThreadUnsafeMethodInvocationsTestSuite.java
Labels: feature, ux, frontend-actions, branch-layout

#1290 Extract EnhancedGraphTable(MouseAdapter|PopupMenuListener) classes to their own files
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTableMouseAdapter.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTablePopupMenuListener.java
Labels: frontend-ui, code quality

#1291 refactor MacheteAnnotator#isBranchNameRepeated
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/BranchLayout.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/highlighting/MacheteAnnotator.java
Labels: code quality

#1296 Fix `TestProcessUtils` to make `gradle build` pass
  .circleci/config.yml
  testCommon/src/testFixtures/java/com/virtuslab/gitmachete/testcommon/TestProcessUtils.java
Labels: bug, build, minor

#1297 In `@IgnoreUIThreadUnsafeCalls`, specify which method calls are ignored
  .github/CODEOWNERS
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSlideInBelowAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/DiscoverAction.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  qual/src/main/java/com/virtuslab/qual/guieffect/IgnoreUIThreadUnsafeCalls.java
  scripts/prohibit-java-class-name-hardcode-in-strings
  src/main/resources/META-INF/plugin.xml
  src/test/java/com/virtuslab/archunit/ClassStructureTestSuite.java
  src/test/java/com/virtuslab/archunit/UIThreadUnsafeMethodInvocationsTestSuite.java
Labels: code quality

#1292 Fix/disable some notifications when machete file opened & focused
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
Labels: ux, frontend-editor

#1284 Remove 'Unreleased' section of CHANGE-NOTES.md
  CONTRIBUTING.md
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  scripts/enforce-change-notes-updated-on-pr-to-master
Labels: build, code quality

#1302 Fix Disposer.register(project, ...) (closes #1288)
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/MacheteFileViewProviderFactory.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/gitrepositoryselection/GitRepositoryComboBox.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
Labels: code quality

#1306 Make checker stub files input to gradle java compile
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFramework.kt
Labels: bug, build

#1304 Get rid of LOG.error based IDE errors for isBranchPresent calls
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
Labels: bug, git-core

#1310 Add missing docs for macOs users
  README.md
Labels: documentation, mac os
