Repository VirtusLab/git-machete-intellij-plugin, pull requests merged in 2022-09, with the labels that each got.

#1103 Correct status displayed on graph during ongoing git repository operation
  CONTRIBUTING.md
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/IGitMacheteRepositorySnapshot.java
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/NullGitMacheteRepositorySnapshot.java
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/OngoingRepositoryOperationType.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepositorySnapshot.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/cell/BranchOrCommitCellRendererComponent.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/DemoGitMacheteRepositorySnapshot.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreRepository.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
Labels: bug, frontend-graph

#1113 Add --empty=drop to rebase options if it is available in git4idea
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSyncToParentByRebaseAction.java
  version.gradle.kts
Labels: frontend-actions

#1112 Make method contain exceptions inside itself, add test for said behaviour
  gitCore/jGit/build.gradle.kts
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  gitCore/jGit/src/test/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepositoryTest.java
Labels: bug, git-core

#1115 Add warning for syncing by merge, remove deprecated dialog usage
  CHANGE-NOTES.md
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseResetToRemoteAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/contextmenu/SyncSelectedToParentByMergeAction.java
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/ResetBranchToRemoteInfoDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/WarnAboutSyncToParentByMergeDialog.kt
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  src/uiTest/resources/project.rhino.js
Labels: ux, frontend-actions

#1083 Ide probe ignore errors by parts of stack trace
  src/uiTest/resources/ideprobe.conf
Labels: testing

#1094 add probe.paths.logExport config to have logs after tests
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  src/uiTest/resources/ideprobe.conf
Labels: feature, testing

#1117 Relax the ban on inner classes
  src/test/java/com/virtuslab/archunit/ClassStructureTestSuite.java
Labels: code quality

#1106 Contribution.md: info on bundled plugins and gradle term of service
  CONTRIBUTING.md
Labels: documentation

#1118 Add break lines in possibly too long tooltip text
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/cell/BranchOrCommitCellRendererComponent.java
Labels: ux

#1123 Machete status branch cache
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/StatusBranchHookExecutor.java
Labels: backend

#1133 Add hyperlink to warning dialog
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/contextmenu/SyncSelectedToParentByMergeAction.java
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  scripts/prohibit-properties-unused-keys
Labels: ux

#1124 close milestone on release
  .circleci/config.yml
  docker/Dockerfile
  scripts/close-milestone
Labels: ci

#1137 Apply minor fixes before release v3.0.1
  CHANGE-NOTES.md
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSyncToParentByRebaseAction.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  gitCore/jGit/src/test/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepositoryTest.java
Labels: code quality, release

#1136 Check if all local branches are managed before suggesting rediscovery
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/IBranchLayout.java
  frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/RediscoverSuggester.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/root/GitMachetePanel.java
Labels: ux

#1132 Change Kotlin properties to private + add repro for IllegalCallableAccessException on KProperty.call()
  build.gradle.kts
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/DeleteBranchOnSlideOutSuggestionDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/GitNewCommitMessageActionDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/GraphTableDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/OverrideForkPointDialog.kt
  frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/SlideInDialog.kt
  scripts/prohibit-kotlin-private-fields
  scripts/run-pre-build-checks
  src/test/kotlin/KPropertyTestSuite.kt
  version.gradle.kts
Labels: code quality

#1143 fixing the CI in #1142
  .circleci/config.yml
  version.gradle.kts
Labels: bug

#1146 fixing the CI in #1142
  .circleci/config.yml
Labels: bug

#1149 Change property name from headless to virtualDisplay
  .circleci/config.yml
  CONTRIBUTING.md
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  docker/Dockerfile
Labels: documentation, testing

#1139 Plugin sign
  .gitignore
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
Labels: build, distribution

#1153 New optional to nullable
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/IGitMacheteRepositorySnapshot.java
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/NullGitMacheteRepositorySnapshot.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/GitMacheteRepository.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/PreRebaseHookExecutor.java
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/StatusBranchHookExecutor.java
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/unit/BaseGitMacheteRepositoryUnitTestSuite.java
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/unit/GitMacheteRepository_deriveParentAwareForkPointUnitTestSuite.java
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/unit/GitMacheteRepository_deriveRelationToRemoteUnitTestSuite.java
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/unit/UnitTestUtils.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/BranchLayoutException.java
  branchLayout/impl/src/test/java/com/virtuslab/branchlayout/unit/BranchLayoutFileReaderTestSuite.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSlideOutAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseSyncToParentByRebaseAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/DiscoverAction.java
  frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/vfsutils/GitVfsUtils.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/MacheteFileUtils.java
  frontend/file/src/main/java/com/virtuslab/gitmachete/frontend/file/highlighting/MacheteAnnotator.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/RediscoverSuggester.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/cell/BranchOrCommitCellRendererComponent.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/DemoGitMacheteRepositorySnapshot.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/GitMacheteRepositoryUpdateBackgroundable.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreHeadSnapshot.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreLocalBranchSnapshot.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreReflogEntry.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreRepository.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreCommitHash.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreHeadSnapshot.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreLocalBranchSnapshot.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreReflogEntry.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  gitCore/jGit/src/test/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepositoryTest.java
Labels: code quality

#1162 Made where-to-find-the-plugin-tab in README obvious
  README.md
Labels: documentation

#1165 Exclude timestamp from the input to hash of intellijVersions.properties
  .circleci/config.yml
Labels: bug, ci

#1169 Prevent merging branches to master accidentally
  scripts/prohibit-direct-merges-to-master
  scripts/run-pre-build-checks
Labels: bug, ci

#1176 Improve osx-related parts in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1174 Provide more specific guidelines on change notes
  CHANGE-NOTES.md
  CONTRIBUTING.md
Labels: documentation, distribution

#1177 Add GitVfsUtils function call instead of intellij method
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/OpenMacheteFileAction.java
Labels: code quality

#1180 Fix java docs on methods that now return a nullable instead of an option
  backend/impl/src/main/java/com/virtuslab/gitmachete/backend/impl/hooks/PreRebaseHookExecutor.java
  frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/vfsutils/GitVfsUtils.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreHeadSnapshot.java
  gitCore/api/src/main/java/com/virtuslab/gitcore/api/IGitCoreReflogEntry.java
Labels: documentation

#1156 Add a project property that enables to runIde with different IDE versions
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Dependencies.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijPlugin.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateIntellijVersions.kt
Labels: build

#1185 Fix env vars needed for plugin signing
  .circleci/config.yml
  CONTRIBUTING.md
  build.gradle.kts
Labels: bug, build, ci, EXPEDITE

#1186 Release v3.0.2, approach #2
  .circleci/config.yml
  CONTRIBUTING.md
  build.gradle.kts
Labels: release

#1178 Use the actual path to plugin zip in CI
  .circleci/config.yml
  CONTRIBUTING.md
  build.gradle.kts
  scripts/verify-artifact-contents
  version.gradle.kts
Labels: build, code quality

#1184 get next and previous branch in the BranchLayout
  backend/api/src/main/java/com/virtuslab/gitmachete/backend/api/NullBranchLayout.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/BranchLayout.java
  branchLayout/api/src/main/java/com/virtuslab/branchlayout/api/IBranchLayout.java
  branchLayout/impl/src/test/java/com/virtuslab/branchlayout/unit/BranchLayoutTestSuite.java
Labels: branch-layout

#1189 use signed plugin zip as an attachment to release
  .circleci/config.yml
  build.gradle.kts
Labels: build

#1191 Enable ctrl click as right click for mac os
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
Labels: bug, frontend-ui, SEVERE, mac os

#1179 gh instead of hub
  .circleci/config.yml
  docker/Dockerfile
  scripts/enforce-change-notes-updated-on-pr-to-master
Labels: code quality

#1193 improve toggle listing commits description
  CHANGE-NOTES.md
  docs/features.md
Labels: documentation

#1194 Remove outdated part of `edit machete file` guide
  docs/features.md
Labels: documentation

#1197 Improve user facing notes and comments for 3.0.3
  CHANGE-NOTES.md
  CONTRIBUTING.md
  docs/features.md
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/EnhancedGraphTable.java
Labels: documentation
