Repository VirtusLab/git-machete-intellij-plugin, pull requests merged in 2022-12, with the labels that each got.

#1370 Do not use fmt as extension method in scope of SlideOutBackgroundable
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/backgroundables/SlideOutBackgroundable.java
Labels: bug, ci, code quality

#1372 Bump io.freefair.gradle aspectj-plugin to 6.6
  gradle/libs.versions.toml
Labels: code quality

#1378 Bump spotless-plugin-gradle to 6.12.0
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/Spotless.kt
  gradle/libs.versions.toml
Labels: build

#1381 Use `showStandardStreams` instead of modifying `events` in `testLogging`
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UiTests.kt
  gitCore/jGit/build.gradle.kts
Labels: build, code quality

#1395 Switch from `RevSort.TOPO` to `RevSort.COMMIT_TIME_DESC` to improve performance on large repos
  .circleci/config.yml
  CHANGE-NOTES.md
  build.gradle.kts
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  scripts/close-milestone
  src/test/java/com/virtuslab/archunit/ForbiddenFieldsTestSuite.java
Labels: backend, performance

#1396 Increase the waiting time for new local branch to be created
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/backgroundables/BaseSlideInBackgroundable.java
Labels: frontend-actions

#1398 Apply minor fixes before the v3.3.0 release
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/base/BaseGitMacheteRepositoryReadyAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/contextmenu/ShowSelectedInGitLogAction.java
  frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/toolbar/TraverseFromCurrentAction.java
  frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/RediscoverSuggester.java
  gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java
  src/test/java/com/virtuslab/archunit/MethodCallsTestSuite.java
  src/test/java/com/virtuslab/archunit/UIThreadUnsafeMethodInvocationsTestSuite.java
Labels: code quality
