Repository VirtusLab/git-machete-intellij-plugin, pull requests merged in 2022-07, with the labels that each got.

#962 Refactored probe.await usage into doAndAwait
  CONTRIBUTING.md
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/RunningIntelliJFixtureExtension.scala
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/UITestSuite.scala
Labels: testing, code quality

#970 Fix ui tests
  src/uiTest/resources/project.rhino.js
Labels: bug, testing

#975 Add condition to not throw exception when artifacts directory not exist or is empty (CI)
  .circleci/config.yml
Labels: ci

#974 Moved two property checking scripts into java tests
  frontend/base/src/test/java/com/virtuslab/gitmachete/resourcebundles/junit/GitMacheteBundlePropertiesTestSuite.java
  scripts/enforce-properties-single-quotes-consistent-with-format-elements
  scripts/prohibit-properties-double-quote-wrapping
  scripts/run-pre-build-checks
Labels: testing

#976 Add information in uiTests about IntelliJ build number
  src/uiTest/scala/com/virtuslab/gitmachete/uitest/UITestSuite.scala
Labels: testing

#966 Add support for git grep regex error
  CONTRIBUTING.md
Labels: documentation, mac os

#978 Bump ide-probe to 0.36.1 to get rid of Ktor/Netty spam in logs
  gradle/libs.versions.toml
  src/uiTest/resources/ideprobe.conf
Labels: minor, testing

#982 Optimize `scripts/prohibit-properties-unused-key`
  scripts/prohibit-properties-unused-keys
Labels: ci, minor, performance

#987 Created a buildSrc/ directory and moved there some of the logic from …
  .gitignore
  build.gradle
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/main/groovy/com.virtuslab.gitmachete.buildsrc/IntellijVersionHelper.groovy
  buildSrc/src/main/groovy/com.virtuslab.gitmachete.buildsrc/UpdateEapBuildNumber.groovy
  scripts/enforce-settings-gradle-match-directories
  scripts/enforce-version-bump
  version.gradle
Labels: build, code quality

#992 Removed the getter for field, imported unrecognized class
  buildSrc/src/main/groovy/com.virtuslab.gitmachete.buildsrc/UpdateEapBuildNumber.groovy
Labels: bug, build

#998 Use ellipsis instead of three dots in GitMacheteBundle.properties
  .circleci/config.yml
  frontend/base/src/main/resources/GitMacheteBundle.properties
  frontend/base/src/test/java/com/virtuslab/gitmachete/resourcebundles/junit/GitMacheteBundlePropertiesTestSuite.java
  src/uiTest/resources/project.rhino.js
Labels: code quality

#1006 Switched UpdateEapBuildNumber to Kotlin
  .circleci/config.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/groovy/com.virtuslab.gitmachete.buildsrc/UpdateEapBuildNumber.groovy
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/SpotlessConfigurator.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
  buildSrc/src/test/kotlin/BuildNumberComparisonTest.kt
  qual/build.gradle.kts
Labels: build, code quality

#1005 Update CLI outputs for backend:impl tests to git-machete v3.11.3
  backend/impl/src/test/java/com/virtuslab/gitmachete/backend/integration/StatusAndDiscoverIntegrationTestSuite.java
  backend/impl/src/test/resources/setup-for-diverged-and-older-than.sh-discover.txt
  backend/impl/src/test/resources/setup-for-diverged-and-older-than.sh-status.txt
  backend/impl/src/test/resources/setup-for-overridden-fork-point.sh-discover.txt
  backend/impl/src/test/resources/setup-for-overridden-fork-point.sh-status.txt
  backend/impl/src/test/resources/setup-for-squash-merge.sh-status.txt
  backend/impl/src/test/resources/setup-for-yellow-edges.sh-discover.txt
  backend/impl/src/test/resources/setup-for-yellow-edges.sh-status.txt
  backend/impl/src/test/resources/setup-with-multiple-remotes.sh-discover.txt
  backend/impl/src/test/resources/setup-with-multiple-remotes.sh-status.txt
  backend/impl/src/test/resources/setup-with-no-remotes.sh-discover.txt
  backend/impl/src/test/resources/setup-with-no-remotes.sh-status.txt
  backend/impl/src/test/resources/setup-with-single-remote.sh-discover.txt
  backend/impl/src/test/resources/setup-with-single-remote.sh-status.txt
  backend/impl/src/test/resources/version.txt
  scripts/prohibit-trailing-whitespace
Labels: testing

#1007 Use version catalog in buildSrc code
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/BuildUtils.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/CheckerFrameworkConfigurator.kt
Labels: build, code quality

#1017 Document adding a configuration for debugging the project
  CONTRIBUTING.md
  docs/debug_configuration.png
Labels: documentation

#1019 Refactor/intellij version classes
  CONTRIBUTING.md
  build.gradle.kts
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/BuildUtils.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersionHelper.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/IntellijVersions.kt
  buildSrc/src/main/kotlin/com/virtuslab/gitmachete/buildsrc/UpdateEapBuildNumber.kt
  scripts/prohibit-kotlin-private-fields
Labels: build, code quality
